Artificier    
    Acid Splash
    Booming Blade
    Create Bonfire
    Dancing Lights
    Fire Bolt
    Frostbite
    Green-Flamde Blade
    Guidance
    Light
    Lightning Lure
    Mage Hand
    Magic Stone
    Mending
    Message
    Poison Spray
    Prestidigitation
    Ray of Frost
    Resistance
    Shocking Grasp
    Spare the Dying
    Sword Burst
    Thorn Whip
    Thunderclap

Sorcerer
